// Package splice defines the SpliceEvent type and a pub/sub queue that
// distributes ESAM signals to all registered packager consumers.
package splice

import (
	"sync"
	"time"
)

// Event carries the parameters extracted from a SCTE-35 splice_insert signal.
type Event struct {
	ID              uint32
	SpliceTime      time.Time
	Duration        time.Duration // break length
	OutOfNetwork    bool
	UniqueProgramID uint16
	ReceivedAt      time.Time

	// Pre-encoded representations generated by the ESAM server.
	Binary []byte // raw SCTE-35 section bytes
	Hex    string // "0x..." for HLS tags
	B64    string // base64 for DASH EventStream
}

// Queue is a simple broadcast queue: one writer (ESAM server), N readers (packagers).
// Subscribers receive a buffered channel; slow subscribers drop events rather than
// blocking the ESAM server.
type Queue struct {
	mu   sync.Mutex
	subs []chan Event
}

// Subscribe returns a channel on which the caller receives SpliceEvents.
// The channel is buffered (size 16); events are dropped if the buffer is full.
func (q *Queue) Subscribe() <-chan Event {
	ch := make(chan Event, 16)
	q.mu.Lock()
	q.subs = append(q.subs, ch)
	q.mu.Unlock()
	return ch
}

// Emit broadcasts e to all current subscribers, dropping the event for any
// subscriber whose buffer is full.
func (q *Queue) Emit(e Event) {
	q.mu.Lock()
	subs := make([]chan Event, len(q.subs))
	copy(subs, q.subs)
	q.mu.Unlock()

	for _, ch := range subs {
		select {
		case ch <- e:
		default:
		}
	}
}
